"""
output_parser.py

Parses raw SLM generations into the 5-field structured format
required by the internship document (Section 5.3):

    SEVERITY, INCIDENT_TYPE, ROOT_CAUSE, SUMMARY, RECOMMENDED_ACTIONS

This is the `parse_model_output` function referenced by the
evaluation script skeleton in document Section 6.2. It is kept in
its own module (standard library only) so that:

  * evaluate.py (Week 4) and fine_tune.py (Week 5) can share it,
  * it can be unit-tested without loading torch/transformers,
  * the Week 8 API can reuse it for response formatting.

The parser is deliberately tolerant: zero-shot models often deviate
from the exact template (markdown bold, numbered field prefixes,
missing fields). Unparseable fields are returned as "" and counted
by the caller — a zero-shot model's format-following failures are
themselves a baseline finding worth reporting (document Week 4:
"run inference with unmodified SLM, measure baseline metrics").
"""

import re

# Valid severity values (document Section 5.3 output schema)
VALID_SEVERITIES = {"CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"}

# The 5 required output fields, in canonical order
FIELDS = (
    "SEVERITY",
    "INCIDENT_TYPE",
    "ROOT_CAUSE",
    "SUMMARY",
    "RECOMMENDED_ACTIONS",
)

# Matches a field header at line start, tolerating:
#   optional list numbering ("1. "), markdown bold ("**"),
#   optional spaces around the colon.
_FIELD_RE = re.compile(
    r"^\s*(?:\d+\s*[.)]\s*)?\*{0,2}"
    r"(SEVERITY|INCIDENT[_ ]TYPE|ROOT[_ ]CAUSE|SUMMARY|RECOMMENDED[_ ]ACTIONS)"
    r"\*{0,2}\s*:\s*(.*)$",
    re.IGNORECASE,
)


def _canonical(field_name: str) -> str:
    """Normalize a matched field header to its canonical key."""
    return field_name.upper().replace(" ", "_")


def parse_model_output(text: str) -> dict:
    """
    Parse one raw model generation into a dict with keys:

        severity            str  (uppercased; "" if missing/invalid)
        incident_type       str
        root_cause          str
        summary             str
        recommended_actions list[str]
        parse_errors        list[str]  (fields missing or invalid)

    Field content may span multiple lines: lines following a field
    header belong to that field until the next header is seen.
    """
    sections: dict[str, list[str]] = {}
    current: str | None = None

    for line in (text or "").splitlines():
        match = _FIELD_RE.match(line)
        if match:
            current = _canonical(match.group(1))
            sections.setdefault(current, [])
            first_content = match.group(2).strip()
            if first_content:
                sections[current].append(first_content)
        elif current is not None:
            stripped = line.strip()
            if stripped:
                sections[current].append(stripped)

    parse_errors = [f for f in FIELDS if f not in sections]

    # --- SEVERITY: must be one of the 5 valid values ---------------
    severity = ""
    if "SEVERITY" in sections and sections["SEVERITY"]:
        raw = sections["SEVERITY"][0].upper()
        # tolerate decoration, e.g. "[HIGH]" or "HIGH — disk failure"
        found = [s for s in VALID_SEVERITIES if re.search(rf"\b{s}\b", raw)]
        if found:
            severity = found[0]
        else:
            parse_errors.append("SEVERITY_INVALID")

    # --- Free-text fields -------------------------------------------
    incident_type = " ".join(sections.get("INCIDENT_TYPE", [])).strip()
    root_cause = " ".join(sections.get("ROOT_CAUSE", [])).strip()
    summary = " ".join(sections.get("SUMMARY", [])).strip()

    # --- RECOMMENDED_ACTIONS: split numbered / bulleted items -------
    actions: list[str] = []
    for item in sections.get("RECOMMENDED_ACTIONS", []):
        cleaned = re.sub(r"^\s*(?:\d+\s*[.)]|[-*•])\s*", "", item).strip()
        if cleaned:
            actions.append(cleaned)

    return {
        "severity": severity,
        "incident_type": incident_type,
        "root_cause": root_cause,
        "summary": summary,
        "recommended_actions": actions,
        "parse_errors": parse_errors,
    }


def parse_reference_output(text: str) -> dict:
    """
    Parse a ground-truth `output` field from the dataset.

    Dataset outputs are generated by templates.format_output and are
    always well-formed, so this is parse_model_output plus a safety
    assertion used during evaluation setup.
    """
    parsed = parse_model_output(text)

    if parsed["parse_errors"]:
        raise ValueError(
            f"Reference output failed to parse "
            f"(errors: {parsed['parse_errors']}). "
            f"Dataset may be corrupted:\n{text[:200]}"
        )

    return parsed
